import type { Metadata } from "next";

import "./globals.css";

import { Poppins } from "next/font/google";

import { Toaster } from "@/components/ui/sonner";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={` ${poppins.className} antialiased`}>
        {children}
        {/* Toast Sonner do Shadcn */}
        <Toaster position="top-right" duration={2000} closeButton={true} />
      </body>
    </html>
  );
}
