// importando o metadata
import type { Metadata } from "next";
// importando o css
import "./globals.css";
// importando a fonte
import { Poppins } from "next/font/google";
// toaster para avisos
import { Toaster } from "@/components/ui/sonner";
// importando o footer
import Footer from "@/components/Footer";
// criando a fonte
const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});
// criando metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${poppins.className} antialiased`}>
        {children}
        {/* Toast Sonner do Shadcn */}
        <Toaster position="top-right" duration={2000} closeButton={true} />
        <Footer />
      </body>
    </html>
  );
}
